<?xml version="1.0"?>
<!DOCTYPE OpenGLAPI [
<!ELEMENT OpenGLAPI (category+)>
<!ELEMENT category (type*, enum*, function*)>
<!ELEMENT type EMPTY>
<!ELEMENT enum EMPTY>
<!ELEMENT function (param*, return?, glx?)>
<!ELEMENT param EMPTY>
<!ELEMENT return EMPTY>
<!ELEMENT glx EMPTY>

<!ATTLIST category name   CDATA #REQUIRED
                   number CDATA #IMPLIED>
<!ATTLIST type     name   CDATA #REQUIRED
                   size   CDATA #REQUIRED
                   glx_name CDATA #IMPLIED>
<!ATTLIST enum     name   CDATA #REQUIRED
                   value  CDATA #REQUIRED>
<!ATTLIST function name   CDATA #REQUIRED
                   offset CDATA #REQUIRED
                   vectorequiv CDATA #IMPLIED>
<!ATTLIST param    name   CDATA #REQUIRED
                   type   CDATA #REQUIRED
                   count  CDATA #IMPLIED
                   counter  CDATA #IMPLIED
                   count_scale  CDATA #IMPLIED
                   output   CDATA #IMPLIED
		   img_width     CDATA #IMPLIED
		   img_height    CDATA #IMPLIED
		   img_depth     CDATA #IMPLIED
		   img_extent    CDATA #IMPLIED
		   img_xoff      CDATA #IMPLIED
		   img_yoff      CDATA #IMPLIED
		   img_zoff      CDATA #IMPLIED
		   img_woff      CDATA #IMPLIED
		   img_format    CDATA #IMPLIED
		   img_type      CDATA #IMPLIED
		   img_target    CDATA #IMPLIED
		   img_send_null CDATA #IMPLIED
		   img_null_flag CDATA #IMPLIED
		   img_pad_dimensions CDATA #IMPLIED
                   variable_param  CDATA #IMPLIED>
<!ATTLIST return   type     CDATA #REQUIRED>
<!ATTLIST glx      rop      CDATA #IMPLIED
                   sop      CDATA #IMPLIED
                   vendorpriv  CDATA #IMPLIED
                   large    CDATA #IMPLIED
                   doubles_in_order CDATA #IMPLIED
                   always_array CDATA #IMPLIED
                   handcode CDATA #IMPLIED
                   ignore   CDATA #IMPLIED>
]>

<!--
The various attributes for param and glx have the meanings listed below.
When adding new functions, please annote them correct.  In most cases this
will just mean adding a '<glx ignore="true"/>' tag.
    
param:
     name - name of the parameter
     type - fully qualified type (e.g., with "const", etc.)
     count - for counted arrays (e.g., the 'lists' parameter to glCallLists),
         the parameter or literal that represents the count.  For functions
	 like glVertex3fv it will be a litteral, for others it will be one of
	 the parameters.
     counter - this parameter is a counter that will be referenced by the
         'count' attribute in another parameter.
     count_scale - literal value scale factor for the 'count' attribute.
         See ProgramParameters4dvNV for an example.
     output - this parameter is used to store the output of the function.
     variable_param - name of parameter used to determine the number of
         elements referenced by this parameter.  This should be the name of a
         single enum parameter.  Most of the gl*Parameter[if]v functions use
	 this.  Additionally, the enums that can be passed should be properly
	 annotated.
     img_width / img_height / img_depth / img_extent - name of parameters
         (or hardcoded integer) used for the dimensions of pixel data.
     img_xoff / img_yoff / img_zoff / img_woff - name of parameters used
         for x, y, z, and w offsets of pixel data.
     img_format - name of parameter used as the pixel data format.
     img_type - name of parameter used as the pixel data type.
     img_target - name of parameter used as a texture target.  Non-texture
        pixel data should hardcode 0.
     img_send_null - boolean flag to determine if blank pixel data should
        be sent when a NULL pointer is passed.  This is only used by
	TexImage1D and TexImage2D.
     img_null_flag - boolean flag to determine if an extra flag is used to
        determine if a NULL pixel pointer was passed.  This is used by
	TexSubImage1D, TexSubImage2D, TexImage3D and others.
     img_pad_dimensions - boolean flag to determine if dimension data and
        offset data should be padded to the next even number of dimensions.
	For example, this will insert an empty "height" field after the
	"width" field in the protocol for TexImage1D.

glx:
     rop - Opcode value for "render" commands
     sop - Opcode value for "single" commands
     vendorpriv - Opcode value for vendor private (or vendor private with
         reply) commands
     large - set to "true" of the render command can use RenderLarge protocol.
     doubles_in_order - older commands always put GLdouble data at the
         start of the render packet.  Newer commands (e.g., 
         ProgramEnvParameter4dvARB) put the in the order that they appear
         in the parameter list.
     always_array - some single commands take reply data as an array or as
         return value data (e.g., glGetLightfv).  Other single commands take
         reply data only as an array (e.g., glGetClipPlane).
     handcode - some functions are just too complicated to generate 
         (e.g., glSeperableFilter2D) or operate only on client-side data
         (e.g., glVertexPointer) and must be handcoded.
     ignore - some functions have an entry in the dispatch table, but aren't
         suitable for protocol implementation (e.g., glLockArraysEXT).  This
	 also applies to functions that don't have any GLX protocol specified
	 (e.g., glGetFogFuncSGIS).
-->

<OpenGLAPI>

<!-- Core versions sorted by version number. -->

<category name="1.0">
    <enum name="FALSE"                                    value="0x0"/>
    <enum name="TRUE"                                     value="0x1"/>
    <enum name="ZERO"                                     value="0x0"/>
    <enum name="ONE"                                      value="0x1"/>
    <enum name="NONE"                                     value="0x0"/>
    <enum name="NO_ERROR"                                 value="0x0"/>
    <enum name="POINTS"                                   value="0x0000"/>
    <enum name="LINES"                                    value="0x0001"/>
    <enum name="LINE_LOOP"                                value="0x0002"/>
    <enum name="LINE_STRIP"                               value="0x0003"/>
    <enum name="TRIANGLES"                                value="0x0004"/>
    <enum name="TRIANGLE_STRIP"                           value="0x0005"/>
    <enum name="TRIANGLE_FAN"                             value="0x0006"/>
    <enum name="QUADS"                                    value="0x0007"/>
    <enum name="QUAD_STRIP"                               value="0x0008"/>
    <enum name="POLYGON"                                  value="0x0009"/>
    <enum name="ACCUM"                                    value="0x0100"/>
    <enum name="LOAD"                                     value="0x0101"/>
    <enum name="RETURN"                                   value="0x0102"/>
    <enum name="MULT"                                     value="0x0103"/>
    <enum name="ADD"                                      value="0x0104"/>
    <enum name="NEVER"                                    value="0x0200"/>
    <enum name="LESS"                                     value="0x0201"/>
    <enum name="EQUAL"                                    value="0x0202"/>
    <enum name="LEQUAL"                                   value="0x0203"/>
    <enum name="GREATER"                                  value="0x0204"/>
    <enum name="NOTEQUAL"                                 value="0x0205"/>
    <enum name="GEQUAL"                                   value="0x0206"/>
    <enum name="ALWAYS"                                   value="0x0207"/>
    <enum name="SRC_COLOR"                                value="0x0300"/>
    <enum name="ONE_MINUS_SRC_COLOR"                      value="0x0301"/>
    <enum name="SRC_ALPHA"                                value="0x0302"/>
    <enum name="ONE_MINUS_SRC_ALPHA"                      value="0x0303"/>
    <enum name="DST_ALPHA"                                value="0x0304"/>
    <enum name="ONE_MINUS_DST_ALPHA"                      value="0x0305"/>
    <enum name="DST_COLOR"                                value="0x0306"/>
    <enum name="ONE_MINUS_DST_COLOR"                      value="0x0307"/>
    <enum name="SRC_ALPHA_SATURATE"                       value="0x0308"/>
    <enum name="FRONT_LEFT"                               value="0x0400"/>
    <enum name="FRONT_RIGHT"                              value="0x0401"/>
    <enum name="BACK_LEFT"                                value="0x0402"/>
    <enum name="BACK_RIGHT"                               value="0x0403"/>
    <enum name="FRONT"                                    value="0x0404"/>
    <enum name="BACK"                                     value="0x0405"/>
    <enum name="LEFT"                                     value="0x0406"/>
    <enum name="RIGHT"                                    value="0x0407"/>
    <enum name="FRONT_AND_BACK"                           value="0x0408"/>
    <enum name="AUX0"                                     value="0x0409"/>
    <enum name="AUX1"                                     value="0x040A"/>
    <enum name="AUX2"                                     value="0x040B"/>
    <enum name="AUX3"                                     value="0x040C"/>
    <enum name="INVALID_VALUE"                            value="0x0501"/>
    <enum name="INVALID_ENUM"                             value="0x0500"/>
    <enum name="INVALID_OPERATION"                        value="0x0502"/>
    <enum name="STACK_OVERFLOW"                           value="0x0503"/>
    <enum name="STACK_UNDERFLOW"                          value="0x0504"/>
    <enum name="OUT_OF_MEMORY"                            value="0x0505"/>
    <enum name="2D"                                       value="0x0600"/>
    <enum name="3D"                                       value="0x0601"/>
    <enum name="3D_COLOR"                                 value="0x0602"/>
    <enum name="3D_COLOR_TEXTURE"                         value="0x0603"/>
    <enum name="4D_COLOR_TEXTURE"                         value="0x0604"/>
    <enum name="PASS_THROUGH_TOKEN"                       value="0x0700"/>
    <enum name="POINT_TOKEN"                              value="0x0701"/>
    <enum name="LINE_TOKEN"                               value="0x0702"/>
    <enum name="POLYGON_TOKEN"                            value="0x0703"/>
    <enum name="BITMAP_TOKEN"                             value="0x0704"/>
    <enum name="DRAW_PIXEL_TOKEN"                         value="0x0705"/>
    <enum name="COPY_PIXEL_TOKEN"                         value="0x0706"/>
    <enum name="LINE_RESET_TOKEN"                         value="0x0707"/>
    <enum name="EXP"                                      value="0x0800"/>
    <enum name="EXP2"                                     value="0x0801"/>
    <enum name="CW"                                       value="0x0900"/>
    <enum name="CCW"                                      value="0x0901"/>
    <enum name="COEFF"                                    value="0x0A00"/>
    <enum name="ORDER"                                    value="0x0A01"/>
    <enum name="DOMAIN"                                   value="0x0A02"/>
    <enum name="CURRENT_COLOR"                            value="0x0B00"/>
    <enum name="CURRENT_INDEX"                            value="0x0B01"/>
    <enum name="CURRENT_NORMAL"                           value="0x0B02"/>
    <enum name="CURRENT_TEXTURE_COORDS"                   value="0x0B03"/>
    <enum name="CURRENT_RASTER_COLOR"                     value="0x0B04"/>
    <enum name="CURRENT_RASTER_INDEX"                     value="0x0B05"/>
    <enum name="CURRENT_RASTER_TEXTURE_COORDS"            value="0x0B06"/>
    <enum name="CURRENT_RASTER_POSITION"                  value="0x0B07"/>
    <enum name="CURRENT_RASTER_POSITION_VALID"            value="0x0B08"/>
    <enum name="CURRENT_RASTER_DISTANCE"                  value="0x0B09"/>
    <enum name="POINT_SMOOTH"                             value="0x0B10"/>
    <enum name="POINT_SIZE"                               value="0x0B11"/>
    <enum name="POINT_SIZE_RANGE"                         value="0x0B12"/>
    <enum name="POINT_SIZE_GRANULARITY"                   value="0x0B13"/>
    <enum name="LINE_SMOOTH"                              value="0x0B20"/>
    <enum name="LINE_WIDTH"                               value="0x0B21"/>
    <enum name="LINE_WIDTH_RANGE"                         value="0x0B22"/>
    <enum name="LINE_WIDTH_GRANULARITY"                   value="0x0B23"/>
    <enum name="LINE_STIPPLE"                             value="0x0B24"/>
    <enum name="LINE_STIPPLE_PATTERN"                     value="0x0B25"/>
    <enum name="LINE_STIPPLE_REPEAT"                      value="0x0B26"/>
    <enum name="LIST_MODE"                                value="0x0B30"/>
    <enum name="MAX_LIST_NESTING"                         value="0x0B31"/>
    <enum name="LIST_BASE"                                value="0x0B32"/>
    <enum name="LIST_INDEX"                               value="0x0B33"/>
    <enum name="POLYGON_MODE"                             value="0x0B40"/>
    <enum name="POLYGON_SMOOTH"                           value="0x0B41"/>
    <enum name="POLYGON_STIPPLE"                          value="0x0B42"/>
    <enum name="EDGE_FLAG"                                value="0x0B43"/>
    <enum name="CULL_FACE"                                value="0x0B44"/>
    <enum name="CULL_FACE_MODE"                           value="0x0B45"/>
    <enum name="FRONT_FACE"                               value="0x0B46"/>
    <enum name="LIGHTING"                                 value="0x0B50"/>
    <enum name="LIGHT_MODEL_LOCAL_VIEWER"                 value="0x0B51">
        <size name="LightModelfv" count="1"/>
        <size name="LightModeliv" count="1"/>
    </enum>
    <enum name="LIGHT_MODEL_TWO_SIDE"                     value="0x0B52">
        <size name="LightModelfv" count="1"/>
        <size name="LightModeliv" count="1"/>
    </enum>
    <enum name="LIGHT_MODEL_AMBIENT"                      value="0x0B53">
        <size name="LightModelfv" count="4"/>
        <size name="LightModeliv" count="4"/>
    </enum>
    <enum name="SHADE_MODEL"                              value="0x0B54"/>
    <enum name="COLOR_MATERIAL_FACE"                      value="0x0B55"/>
    <enum name="COLOR_MATERIAL_PARAMETER"                 value="0x0B56"/>
    <enum name="COLOR_MATERIAL"                           value="0x0B57"/>
    <enum name="FOG"                                      value="0x0B60"/>
    <enum name="FOG_INDEX"                                value="0x0B61">
        <size name="Fogfv" count="1"/>
        <size name="Fogiv" count="1"/>
    </enum>
    <enum name="FOG_DENSITY"                              value="0x0B62">
        <size name="Fogfv" count="1"/>
        <size name="Fogiv" count="1"/>
    </enum>
    <enum name="FOG_START"                                value="0x0B63">
        <size name="Fogfv" count="1"/>
        <size name="Fogiv" count="1"/>
    </enum>
    <enum name="FOG_END"                                  value="0x0B64">
        <size name="Fogfv" count="1"/>
        <size name="Fogiv" count="1"/>
    </enum>
    <enum name="FOG_MODE"                                 value="0x0B65">
        <size name="Fogfv" count="1"/>
        <size name="Fogiv" count="1"/>
    </enum>
    <enum name="FOG_COLOR"                                value="0x0B66">
        <size name="Fogfv" count="4"/>
        <size name="Fogiv" count="4"/>
    </enum>
    <enum name="DEPTH_RANGE"                              value="0x0B70"/>
    <enum name="DEPTH_TEST"                               value="0x0B71"/>
    <enum name="DEPTH_WRITEMASK"                          value="0x0B72"/>
    <enum name="DEPTH_CLEAR_VALUE"                        value="0x0B73"/>
    <enum name="DEPTH_FUNC"                               value="0x0B74"/>
    <enum name="ACCUM_CLEAR_VALUE"                        value="0x0B80"/>
    <enum name="STENCIL_TEST"                             value="0x0B90"/>
    <enum name="STENCIL_CLEAR_VALUE"                      value="0x0B91"/>
    <enum name="STENCIL_FUNC"                             value="0x0B92"/>
    <enum name="STENCIL_VALUE_MASK"                       value="0x0B93"/>
    <enum name="STENCIL_FAIL"                             value="0x0B94"/>
    <enum name="STENCIL_PASS_DEPTH_FAIL"                  value="0x0B95"/>
    <enum name="STENCIL_PASS_DEPTH_PASS"                  value="0x0B96"/>
    <enum name="STENCIL_REF"                              value="0x0B97"/>
    <enum name="STENCIL_WRITEMASK"                        value="0x0B98"/>
    <enum name="MATRIX_MODE"                              value="0x0BA0"/>
    <enum name="NORMALIZE"                                value="0x0BA1"/>
    <enum name="VIEWPORT"                                 value="0x0BA2"/>
    <enum name="MODELVIEW_STACK_DEPTH"                    value="0x0BA3"/>
    <enum name="PROJECTION_STACK_DEPTH"                   value="0x0BA4"/>
    <enum name="TEXTURE_STACK_DEPTH"                      value="0x0BA5"/>
    <enum name="MODELVIEW_MATRIX"                         value="0x0BA6"/>
    <enum name="PROJECTION_MATRIX"                        value="0x0BA7"/>
    <enum name="TEXTURE_MATRIX"                           value="0x0BA8"/>
    <enum name="ATTRIB_STACK_DEPTH"                       value="0x0BB0"/>
    <enum name="CLIENT_ATTRIB_STACK_DEPTH"                value="0x0BB1"/>
    <enum name="ALPHA_TEST"                               value="0x0BC0"/>
    <enum name="ALPHA_TEST_FUNC"                          value="0x0BC1"/>
    <enum name="ALPHA_TEST_REF"                           value="0x0BC2"/>
    <enum name="DITHER"                                   value="0x0BD0"/>
    <enum name="BLEND_DST"                                value="0x0BE0"/>
    <enum name="BLEND_SRC"                                value="0x0BE1"/>
    <enum name="BLEND"                                    value="0x0BE2"/>
    <enum name="LOGIC_OP_MODE"                            value="0x0BF0"/>
    <enum name="LOGIC_OP"                                 value="0x0BF1"/>
    <enum name="AUX_BUFFERS"                              value="0x0C00"/>
    <enum name="DRAW_BUFFER"                              value="0x0C01"/>
    <enum name="READ_BUFFER"                              value="0x0C02"/>
    <enum name="SCISSOR_BOX"                              value="0x0C10"/>
    <enum name="SCISSOR_TEST"                             value="0x0C11"/>
    <enum name="INDEX_CLEAR_VALUE"                        value="0x0C20"/>
    <enum name="INDEX_WRITEMASK"                          value="0x0C21"/>
    <enum name="COLOR_CLEAR_VALUE"                        value="0x0C22"/>
    <enum name="COLOR_WRITEMASK"                          value="0x0C23"/>
    <enum name="INDEX_MODE"                               value="0x0C30"/>
    <enum name="RGBA_MODE"                                value="0x0C31"/>
    <enum name="DOUBLEBUFFER"                             value="0x0C32"/>
    <enum name="STEREO"                                   value="0x0C33"/>
    <enum name="RENDER_MODE"                              value="0x0C40"/>
    <enum name="PERSPECTIVE_CORRECTION_HINT"              value="0x0C50"/>
    <enum name="POINT_SMOOTH_HINT"                        value="0x0C51"/>
    <enum name="LINE_SMOOTH_HINT"                         value="0x0C52"/>
    <enum name="POLYGON_SMOOTH_HINT"                      value="0x0C53"/>
    <enum name="FOG_HINT"                                 value="0x0C54"/>
    <enum name="TEXTURE_GEN_S"                            value="0x0C60"/>
    <enum name="TEXTURE_GEN_T"                            value="0x0C61"/>
    <enum name="TEXTURE_GEN_R"                            value="0x0C62"/>
    <enum name="TEXTURE_GEN_Q"                            value="0x0C63"/>
    <enum name="PIXEL_MAP_I_TO_I"                         value="0x0C70"/>
    <enum name="PIXEL_MAP_S_TO_S"                         value="0x0C71"/>
    <enum name="PIXEL_MAP_I_TO_R"                         value="0x0C72"/>
    <enum name="PIXEL_MAP_I_TO_G"                         value="0x0C73"/>
    <enum name="PIXEL_MAP_I_TO_B"                         value="0x0C74"/>
    <enum name="PIXEL_MAP_I_TO_A"                         value="0x0C75"/>
    <enum name="PIXEL_MAP_R_TO_R"                         value="0x0C76"/>
    <enum name="PIXEL_MAP_G_TO_G"                         value="0x0C77"/>
    <enum name="PIXEL_MAP_B_TO_B"                         value="0x0C78"/>
    <enum name="PIXEL_MAP_A_TO_A"                         value="0x0C79"/>
    <enum name="PIXEL_MAP_I_TO_I_SIZE"                    value="0x0CB0"/>
    <enum name="PIXEL_MAP_S_TO_S_SIZE"                    value="0x0CB1"/>
    <enum name="PIXEL_MAP_I_TO_R_SIZE"                    value="0x0CB2"/>
    <enum name="PIXEL_MAP_I_TO_G_SIZE"                    value="0x0CB3"/>
    <enum name="PIXEL_MAP_I_TO_B_SIZE"                    value="0x0CB4"/>
    <enum name="PIXEL_MAP_I_TO_A_SIZE"                    value="0x0CB5"/>
    <enum name="PIXEL_MAP_R_TO_R_SIZE"                    value="0x0CB6"/>
    <enum name="PIXEL_MAP_G_TO_G_SIZE"                    value="0x0CB7"/>
    <enum name="PIXEL_MAP_B_TO_B_SIZE"                    value="0x0CB8"/>
    <enum name="PIXEL_MAP_A_TO_A_SIZE"                    value="0x0CB9"/>
    <enum name="UNPACK_SWAP_BYTES"                        value="0x0CF0"/>
    <enum name="UNPACK_LSB_FIRST"                         value="0x0CF1"/>
    <enum name="UNPACK_ROW_LENGTH"                        value="0x0CF2"/>
    <enum name="UNPACK_SKIP_PIXELS"                       value="0x0CF4"/>
    <enum name="UNPACK_SKIP_ROWS"                         value="0x0CF3"/>
    <enum name="UNPACK_ALIGNMENT"                         value="0x0CF5"/>
    <enum name="PACK_SWAP_BYTES"                          value="0x0D00"/>
    <enum name="PACK_LSB_FIRST"                           value="0x0D01"/>
    <enum name="PACK_ROW_LENGTH"                          value="0x0D02"/>
    <enum name="PACK_SKIP_ROWS"                           value="0x0D03"/>
    <enum name="PACK_SKIP_PIXELS"                         value="0x0D04"/>
    <enum name="PACK_ALIGNMENT"                           value="0x0D05"/>
    <enum name="MAP_COLOR"                                value="0x0D10"/>
    <enum name="MAP_STENCIL"                              value="0x0D11"/>
    <enum name="INDEX_SHIFT"                              value="0x0D12"/>
    <enum name="INDEX_OFFSET"                             value="0x0D13"/>
    <enum name="RED_SCALE"                                value="0x0D14"/>
    <enum name="RED_BIAS"                                 value="0x0D15"/>
    <enum name="ZOOM_X"                                   value="0x0D16"/>
    <enum name="ZOOM_Y"                                   value="0x0D17"/>
    <enum name="GREEN_SCALE"                              value="0x0D18"/>
    <enum name="GREEN_BIAS"                               value="0x0D19"/>
    <enum name="BLUE_SCALE"                               value="0x0D1A"/>
    <enum name="BLUE_BIAS"                                value="0x0D1B"/>
    <enum name="ALPHA_SCALE"                              value="0x0D1C">
        <size name="TexEnvfv" count="1"/>
        <size name="TexEnviv" count="1"/>
    </enum>
    <enum name="ALPHA_BIAS"                               value="0x0D1D"/>
    <enum name="DEPTH_SCALE"                              value="0x0D1E"/>
    <enum name="DEPTH_BIAS"                               value="0x0D1F"/>
    <enum name="MAX_EVAL_ORDER"                           value="0x0D30"/>
    <enum name="MAX_LIGHTS"                               value="0x0D31"/>
    <enum name="MAX_CLIP_PLANES"                          value="0x0D32"/>
    <enum name="MAX_TEXTURE_SIZE"                         value="0x0D33"/>
    <enum name="MAX_PIXEL_MAP_TABLE"                      value="0x0D34"/>
    <enum name="MAX_ATTRIB_STACK_DEPTH"                   value="0x0D35"/>
    <enum name="MAX_MODELVIEW_STACK_DEPTH"                value="0x0D36"/>
    <enum name="MAX_NAME_STACK_DEPTH"                     value="0x0D37"/>
    <enum name="MAX_PROJECTION_STACK_DEPTH"               value="0x0D38"/>
    <enum name="MAX_TEXTURE_STACK_DEPTH"                  value="0x0D39"/>
    <enum name="MAX_VIEWPORT_DIMS"                        value="0x0D3A"/>
    <enum name="MAX_CLIENT_ATTRIB_STACK_DEPTH"            value="0x0D3B"/>
    <enum name="SUBPIXEL_BITS"                            value="0x0D50"/>
    <enum name="INDEX_BITS"                               value="0x0D51"/>
    <enum name="RED_BITS"                                 value="0x0D52"/>
    <enum name="GREEN_BITS"                               value="0x0D53"/>
    <enum name="BLUE_BITS"                                value="0x0D54"/>
    <enum name="ALPHA_BITS"                               value="0x0D55"/>
    <enum name="DEPTH_BITS"                               value="0x0D56"/>
    <enum name="STENCIL_BITS"                             value="0x0D57"/>
    <enum name="ACCUM_RED_BITS"                           value="0x0D58"/>
    <enum name="ACCUM_GREEN_BITS"                         value="0x0D59"/>
    <enum name="ACCUM_BLUE_BITS"                          value="0x0D5A"/>
    <enum name="ACCUM_ALPHA_BITS"                         value="0x0D5B"/>
    <enum name="NAME_STACK_DEPTH"                         value="0x0D70"/>
    <enum name="AUTO_NORMAL"                              value="0x0D80"/>
    <enum name="MAP1_COLOR_4"                             value="0x0D90">
        <size name="Map1d" count="4"/>
        <size name="Map1f" count="4"/>
    </enum>
    <enum name="MAP1_INDEX"                               value="0x0D91">
        <size name="Map1d" count="1"/>
        <size name="Map1f" count="1"/>
    </enum>
    <enum name="MAP1_NORMAL"                              value="0x0D92">
        <size name="Map1d" count="3"/>
        <size name="Map1f" count="3"/>
    </enum>
    <enum name="MAP1_TEXTURE_COORD_1"                     value="0x0D93">
        <size name="Map1d" count="1"/>
        <size name="Map1f" count="1"/>
    </enum>
    <enum name="MAP1_TEXTURE_COORD_2"                     value="0x0D94">
        <size name="Map1d" count="2"/>
        <size name="Map1f" count="2"/>
    </enum>
    <enum name="MAP1_TEXTURE_COORD_3"                     value="0x0D95">
        <size name="Map1d" count="3"/>
        <size name="Map1f" count="3"/>
    </enum>
    <enum name="MAP1_TEXTURE_COORD_4"                     value="0x0D96">
        <size name="Map1d" count="4"/>
        <size name="Map1f" count="4"/>
    </enum>
    <enum name="MAP1_VERTEX_3"                            value="0x0D97">
        <size name="Map1d" count="3"/>
        <size name="Map1f" count="3"/>
    </enum>
    <enum name="MAP1_VERTEX_4"                            value="0x0D98">
        <size name="Map1d" count="4"/>
        <size name="Map1f" count="4"/>
    </enum>
    <enum name="MAP2_COLOR_4"                             value="0x0DB0">
        <size name="Map2d" count="4"/>
        <size name="Map2f" count="4"/>
    </enum>
    <enum name="MAP2_INDEX"                               value="0x0DB1">
        <size name="Map2d" count="1"/>
        <size name="Map2f" count="1"/>
    </enum>
    <enum name="MAP2_NORMAL"                              value="0x0DB2">
        <size name="Map2d" count="3"/>
        <size name="Map2f" count="3"/>
    </enum>
    <enum name="MAP2_TEXTURE_COORD_1"                     value="0x0DB3">
        <size name="Map2d" count="1"/>
        <size name="Map2f" count="1"/>
    </enum>
    <enum name="MAP2_TEXTURE_COORD_2"                     value="0x0DB4">
        <size name="Map2d" count="2"/>
        <size name="Map2f" count="2"/>
    </enum>
    <enum name="MAP2_TEXTURE_COORD_3"                     value="0x0DB5">
        <size name="Map2d" count="3"/>
        <size name="Map2f" count="3"/>
    </enum>
    <enum name="MAP2_TEXTURE_COORD_4"                     value="0x0DB6">
        <size name="Map2d" count="4"/>
        <size name="Map2f" count="4"/>
    </enum>
    <enum name="MAP2_VERTEX_3"                            value="0x0DB7">
        <size name="Map2d" count="3"/>
        <size name="Map2f" count="3"/>
    </enum>
    <enum name="MAP2_VERTEX_4"                            value="0x0DB8">
        <size name="Map2d" count="4"/>
        <size name="Map2f" count="4"/>
    </enum>
    <enum name="MAP1_GRID_DOMAIN"                         value="0x0DD0"/>
    <enum name="MAP1_GRID_SEGMENTS"                       value="0x0DD1"/>
    <enum name="MAP2_GRID_DOMAIN"                         value="0x0DD2"/>
    <enum name="MAP2_GRID_SEGMENTS"                       value="0x0DD3"/>
    <enum name="TEXTURE_1D"                               value="0x0DE0"/>
    <enum name="TEXTURE_2D"                               value="0x0DE1"/>
    <enum name="FEEDBACK_BUFFER_POINTER"                  value="0x0DF0"/>
    <enum name="FEEDBACK_BUFFER_SIZE"                     value="0x0DF1"/>
    <enum name="FEEDBACK_BUFFER_TYPE"                     value="0x0DF2"/>
    <enum name="SELECTION_BUFFER_POINTER"                 value="0x0DF3"/>
    <enum name="SELECTION_BUFFER_SIZE"                    value="0x0DF4"/>
    <enum name="TEXTURE_WIDTH"                            value="0x1000"/>
    <enum name="TEXTURE_HEIGHT"                           value="0x1001"/>
    <enum name="TEXTURE_BORDER"                           value="0x1005"/>
    <enum name="TEXTURE_COMPONENTS"                       value="0x1003"/>
    <enum name="TEXTURE_BORDER_COLOR"                     value="0x1004">
        <size name="TexParameterfv" count="4"/>
        <size name="TexParameteriv" count="4"/>
    </enum>
    <enum name="DONT_CARE"                                value="0x1100"/>